# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testfiltersyears' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testfiltersyears' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(908, 1016)
    @driver.find_element(:css, '#panelsStayOpen-headingTwo > .accordion-button').click
    @driver.find_element(:css, '#panelsStayOpen-collapseTwo .form-check:nth-child(12) > #flexCheckDefault').click
    @driver.find_element(:id, 'btn-acc').click
    @driver.find_element(:css, '.card:nth-child(1) .card-title').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq('Hot Wheels. За гранью воображения')
    @driver.close
  end
end
