# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testopenedituserwithoutsighin' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testopenedituserwithoutsighin' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1846, 1016)
    @driver.find_element(:link_text, 'Мой кабинет').click
    expect(@driver.find_element(:css, 'h2').text).to eq('Войти')
    @driver.find_element(:link_text, 'Главная').click
    @driver.find_element(:css, '.card:nth-child(1) .card-title').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq('Зеленая миля')
    @driver.close
  end
end
