# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testaddcomment' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testaddcomment' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1846, 1016)
    @driver.find_element(:link_text, 'Войти').click
    @driver.find_element(:id, 'user_email').send_keys('danil_nikolaev_96@bk.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '#panelsStayOpen-headingTwo > .accordion-button').click
    @driver.find_element(:css, '#panelsStayOpen-collapseTwo .form-check:nth-child(87) > #flexCheckDefault').click
    @driver.find_element(:id, 'btn-acc').click
    @driver.find_element(:link_text, 'подробнее').click
    @driver.find_element(:id, 'comment').click
    @driver.find_element(:id, 'comment').send_keys('test')
    @driver.find_element(:css, '.back-btn').click
    @driver.find_element(:css, '.comment > h5').click
    expect(@driver.find_element(:css, '.comment > h5').text).to eq('danil_nikolaev_96@bk.ru')
    @driver.find_element(:css, '.comment > p').click
    expect(@driver.find_element(:css, '.comment > p').text).to eq('test')
    @driver.find_element(:link_text, 'Выйти').click
    @driver.close
  end
end
