# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testopenfilm' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testopenfilm' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1846, 1016)
    @driver.find_element(:link_text, 'подробнее').click
    @driver.find_element(:css, '.film-title').click
    expect(@driver.find_element(:css, '.film-title').text).to eq('Зеленая миля')
    @driver.find_element(:link_text, 'Назад').click
    @driver.find_element(:css, '.card:nth-child(1) .card-title').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq('Зеленая миля')
    @driver.close
  end
end
