# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testfiltergenres' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testfiltergenres' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1846, 1016)
    @driver.find_element(:id, 'flexCheckDefault').click
    @driver.find_element(:id, 'btn-acc').click
    @driver.find_element(:css, '.card:nth-child(1) .card-title').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq('Зеленая миля')
    @driver.find_element(:id, 'flexCheckDefault').click
    @driver.find_element(:css, '#panelsStayOpen-collapseOne .form-check:nth-child(3) > #flexCheckDefault').click
    @driver.find_element(:id, 'btn-acc').click
    @driver.find_element(:css, '.card:nth-child(1) .card-title').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq('Рэдволл: Фильм')
    @driver.close
  end
end
