# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testsignup' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testsignup' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1846, 1016)
    @driver.find_element(:link_text, 'Войти').click
    @driver.find_element(:link_text, 'Зарегестрироваться').click
    @driver.find_element(:id, 'user_email').send_keys('test@mail.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:id, 'user_password_confirmation').click
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.card:nth-child(1) .card-title').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq('Зеленая миля')
    @driver.find_element(:link_text, 'Мой кабинет').click
    @driver.find_element(:css, 'h2').click
    expect(@driver.find_element(:css, 'h2').text).to eq('Редактировать профиль')
    @driver.find_element(:link_text, 'Назад').click
    @driver.find_element(:css, '.card:nth-child(1) .card-title').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq('Зеленая миля')
    @driver.find_element(:link_text, 'Выйти').click
    @driver.find_element(:css, '.card:nth-child(1) .card-title').click
    expect(@driver.find_element(:css, '.card:nth-child(1) .card-title').text).to eq('Зеленая миля')
    @driver.close
  end
end
