# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testbaumrating' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testbaumrating' do
    @driver.get('http://localhost:3000/')
    @driver.manage.resize_to(1846, 1016)
    @driver.find_element(:link_text, 'Войти').click
    @driver.find_element(:id, 'user_email').send_keys('danil_nikolaev_96@bk.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '#panelsStayOpen-headingTwo > .accordion-button').click
    @driver.find_element(:css, '#panelsStayOpen-collapseTwo .form-check:nth-child(89) > #flexCheckDefault').click
    @driver.find_element(:id, 'btn-acc').click
    @driver.find_element(:link_text, 'подробнее').click
    @driver.find_element(:css, 'label:nth-child(6)').click
    @driver.find_element(:css, '.film-text:nth-child(5)').click
    @driver.find_element(:link_text, 'Выйти').click
    @driver.close
  end
end
